wutsi:
  application:
    env: test
    server-url: ${wutsi.application.chat-url}
  platform:
    image:
      type: image-kit
      image-kit:
        origin-url: "https://s3.amazonaws.com/int-wutsi"
        endpoint-url: "https://ik.imagekit.io/cx8qxsgz4d"
    messaging:
      url-shortener:
        type: bitly
        bitly:
          access-token: ${BITLY_ACCESS_TOKEN}
    security:
      api-key: ${API_KEY}
      verify-token: true
      token-blacklist:
        type: redis
        redis:
          url: ${REDIS_URL}
    storage:
      type: aws
      aws:
        bucket: int-wutsi
    stream:
      type: rabbitmq
      rabbitmq:
        url: ${CLOUDAMQP_URL}
