wutsi:
  application:
    env: prod
    server-url: ${wutsi.application.chat-url}
    asset-url: https://prod-wutsi.s3.amazonaws.com
  platform:
    image:
      type: image-kit
      image-kit:
        origin-url: "https://s3.amazonaws.com/prod-wutsi"
        endpoint-url: "https://ik.imagekit.io/toifevuwjn"
    messaging:
      url-shortener:
        type: bitly
        bitly:
          access-token: ${BITLY_ACCESS_TOKEN}
    security:
      api-key: ${API_KEY}
      verify-token: true
    storage:
      type: aws
      aws:
        bucket: prod-wutsi
    stream:
      type: rabbitmq
      rabbitmq:
        url: ${CLOUDAMQP_URL}
